name: Update readme
run-name: Update readme
on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows:
      - Build lists
      - Build NSFW Blocklist
    types:
      - completed
  push:
    paths:
      - 'scripts/update_readme.sh'
permissions:
  contents: write

jobs:
  update-readme:
    # Do not run if workflow_run failed/cancelled (still allows workflow_dispatch and workflow_call)
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: update_readme.sh
        run: bash scripts/update_readme.sh
        env:
          BLOCKLIST_DESCRIPTION: ${{ vars.BLOCKLIST_DESCRIPTION }}

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: update readme"
          git push -q